### ISSUE TITLE
Supporting `input` event as an event function.

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [AkaraChen/nashi#13]
I have checked the supported event type list as such:
![image](https://user-images.githubusercontent.com/108161206/200606840-24d84d17-7f0d-42e0-9d04-9c71110c68d8.png)
And, it doesn't seem to support the `input` event as of right now. Would it be possible to support this as I usually prefer using `input` as opposed to `change` when it comes to form contents.

Thanks a lot!
~ Jayman.

**Comment by AkaraChen** [comment]
Added in `0.0.7`
