### ISSUE TITLE
展开运算符存在长度限制问题

### ISSUE THREAD

**Issue by siaikin** [AkaraChen/nashi#21]
[source code](https://github.com/AkaraChen/nashi/blob/main/src/core.js#L11)

展开运算符[^1]在 querySelectAll 场景下很有可能超出 65536[^2] 的长度限制

[^1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#description

[^2]: https://bugs.webkit.org/show_bug.cgi?id=80797

**Comment by AkaraChen** [comment]
[commit](https://github.com/AkaraChen/nashi/commit/a056d0e83a5b2508c4f152919b0068641aad555e)， 全都改成了 `Array.from`
