### ISSUE TITLE
Lacking functions

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [AkaraChen/nashi#6]
Hey, I have run into usecases where I need specific functions that are not supplied at the moment.

I understand that it is still early days for this library, and I am really loving it so far!
However, I would like these functions to be implemented ASAP as it will make the Dev Ex better in my opinion.

`append` - This function would take a list of `QueryResult` elements and append them as children to the targeted node, as such:
```ts
append(...elements: QueryResult[])
```
Example:
```js
const parentElement = nashi.create("div");
const childElement = nashi.create("p");
parentElement.append(childElement);
```

`attr` - This function would take two strings (the first being the attribute name), and the second being the new value to set the attribute to, as such:
```ts
attr(name: string, value: string)
```

Example:
```js
const element = nashi.create("input");
element.attr("value", "hello world!");
// OR
element.attr("type", "text");
```

I also want the types, such as `QueryResult` and `Input`, to be exposed for personal use.
If they are already exposed, I wasn't able to find the relevant documentation.

Thanks heaps!
- Jayman

**Comment by AkaraChen** [comment]
Work in progress.

**Comment by AkaraChen** [comment]
`attr()` and `append()` have been added.
`append()` can only take one `QueryResult` args, but you can use `nashi.merge()` to merge two `QueryResult`

```ts
const element1 = nashi.create('p')
const element2 = nashi.create('div')
const merged = nashi.merge(element1, element2)
```
Type `QueryResult`, `Core`, `Input` are exported.

**Comment by jaymanmatthewsdev** [comment]
Hey, thankyou for the very speedy response and additions!

They all seem to be working as expected! Huge props to you!

**I am going to close this issue as the issues/recommendations I suggested have all been successfully implemented.**
