### ISSUE TITLE
Event handler types do not include the possibility of the Event parameter.

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [AkaraChen/nashi#7]
Hey, I have run into one more issue regarding Typescript specifically.

I am going to use the `click` QueryResult function as an example.

Currently, the type is as follows
```ts
click(handler: () => void);
```

I would like it to change to something like this:
```ts
click(handler: (event?: Event) => void);
```

This way, we won't need to do something like this:
```ts
const button = nashi.create("button");
const handleClick = (evt: PointerEvent) => {
  console.log("clicked", evt);
}
button.click(handleClick as () => void) // have to typecast to remove Typescript error.
```

**Comment by AkaraChen** [comment]
It will included in the next release

**Comment by AkaraChen** [comment]
Added in `0.0.6`

**Comment by jaymanmatthewsdev** [comment]
Ay, thankyou for this and all of the work you are doing!

I am going to work on some side-projects using this library now.
I am loving this library and am hoping that it gains traction!

**Comment by AkaraChen** [comment]
All of your advices are useful,  thank you for your help!
